var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__6f9943e4._.js")
R.c("server/chunks/ssr/Brocan+Blogs_nextjs-mdx-blog_1560047f._.js")
R.c("server/chunks/ssr/Brocan+Blogs_nextjs-mdx-blog_c13a5f41._.js")
R.c("server/chunks/ssr/[root-of-the-server]__b56a5227._.js")
R.c("server/chunks/ssr/c4aff_next_dist_717d0652._.js")
R.c("server/chunks/ssr/c4aff_next_dist_f47c52d8._.js")
R.c("server/chunks/ssr/Brocan+Blogs_nextjs-mdx-blog_src_app_579064bb._.js")
R.c("server/chunks/ssr/c4aff_next_dist_client_components_builtin_global-error_cf67484d.js")
R.c("server/chunks/ssr/Brocan+Blogs_nextjs-mdx-blog_src_d7de9f26._.js")
R.c("server/chunks/ssr/Brocan+Blogs_nextjs-mdx-blog_67cd1e85._.js")
R.c("server/chunks/ssr/c4aff_next_dist_client_components_0739a556._.js")
R.c("server/chunks/ssr/c4aff_next_dist_client_components_builtin_unauthorized_1bb2334c.js")
R.c("server/chunks/ssr/Brocan+Blogs_nextjs-mdx-blog__next-internal_server_app_page_actions_4ffbd30d.js")
R.m(90770)
module.exports=R.m(90770).exports
