var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/pulsegym-pro/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__c5566ca0._.js")
R.c("server/chunks/ssr/Brocan+Blogs_nextjs-mdx-blog_1560047f._.js")
R.c("server/chunks/ssr/Brocan+Blogs_nextjs-mdx-blog_73386d6b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__b56a5227._.js")
R.c("server/chunks/ssr/c4aff_next_dist_717d0652._.js")
R.c("server/chunks/ssr/c4aff_next_dist_f47c52d8._.js")
R.c("server/chunks/ssr/Brocan+Blogs_nextjs-mdx-blog_src_app_579064bb._.js")
R.c("server/chunks/ssr/c4aff_next_dist_client_components_builtin_global-error_cf67484d.js")
R.c("server/chunks/ssr/Brocan+Blogs_nextjs-mdx-blog_src_d7de9f26._.js")
R.c("server/chunks/ssr/Brocan+Blogs_nextjs-mdx-blog_67cd1e85._.js")
R.c("server/chunks/ssr/c4aff_next_dist_client_components_0739a556._.js")
R.c("server/chunks/ssr/c4aff_next_dist_client_components_builtin_unauthorized_1bb2334c.js")
R.c("server/chunks/ssr/71261_nextjs-mdx-blog__next-internal_server_app_pulsegym-pro_page_actions_cf0c2046.js")
R.m(53739)
module.exports=R.m(53739).exports
